igis_udm/urls.py
from django.urls import path, re_path
from .views import *
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PlaceSitemap, HospitalSitemap

urlpatterns = [
    re_path(r'^hospital/(?P<slug>[-\w]+)/$', HospitalDetailView.as_view(), name='hospital'),
    path(r'login/', HospitalLoginFormView.as_view(), name='login'),
    path(r'logout/', HospitalLogOutFormView.as_view(), name='logout'),
    path(r'get_time/', HospitalGetPersonTime.as_view(), name='get_time'),
    path(r'signin/', SignInFormView.as_view(), name='signin'),
    path(r'signout/', SignOutFormView.as_view(), name='signout'),
    path('sitemap.xml', sitemap, {'sitemaps': {'Place': PlaceSitemap, 'Hospital': HospitalSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
    path(r'contacts/', ContactView.as_view(), name='contacts'),
    path(r'contacts/success/', ContactSuccessView.as_view(), name='contacts_success'),
    re_path(r'^(?P<slug>\w+)/$', PlaceDetailView.as_view(), name='place'),
    re_path(r'^$', PlaceListView.as_view(), name='place_list'),
]

igis_udm/models.py
from django.db import models
from django.urls import reverse_lazy


class SEOitems(models.Model):
    head_title = models.CharField(max_length=255, unique=True)
    head_description = models.CharField(max_length=255, unique=True)
    head_keywords = models.CharField(max_length=255, unique=True)


class Place(models.Model):
    name = models.CharField('название', max_length=255, unique=True)
    igis_name = models.CharField(max_length=255, null=True, blank=True)
    seo = models.ForeignKey(SEOitems, verbose_name='seo', on_delete=models.PROTECT, null=True, blank=True)
    igis_url = models.URLField(max_length=255, null=True, blank=True)
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse_lazy('place', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']
        app_label = 'igis_udm'

    def __str__(self):
        return self.name


class Hospital(models.Model):
    name = models.CharField('название', max_length=255, unique=True)
    igis_name = models.CharField(max_length=255, null=True, blank=True)
    seo = models.ForeignKey(SEOitems, verbose_name='seo', on_delete=models.PROTECT, null=True, blank=True)
    igis_url = models.URLField(max_length=255, null=True, blank=True, unique=True)
    igis_obj = models.SmallIntegerField(unique=True)
    place = models.ForeignKey(Place, verbose_name='населенный пункт', on_delete=models.CASCADE)
    phone = models.CharField('телефон', max_length=100, null=True, blank=True)
    slug = models.SlugField(unique=True, max_length=255)
    address = models.CharField('адрес', max_length=255, null=True, blank=True)
    site_url = models.URLField(max_length=255, null=True, blank=True)
    x_coord = models.CharField(max_length=24, null=True, blank=True)
    y_coord = models.CharField(max_length=24, null=True, blank=True)
    image = models.ImageField(upload_to='igis_udm/full',
                              height_field='image_height',
                              width_field='image_width',
                              max_length=256,
                              blank=True,
                              null=True)
    igis_image_url = models.CharField(max_length=255, null=True, blank=True)
    image_width = models.SmallIntegerField(blank=True, null=True)
    image_height = models.SmallIntegerField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse_lazy('hospital', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']
        verbose_name = 'мед учереждение'
        verbose_name_plural = 'мед учереждения'
        app_label = 'igis_udm'

    def __str__(self):
        return self.name


class Speciality(models.Model):
    name = models.CharField('название', max_length=255, unique=True, blank=True, null=True)
    slug = models.SlugField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse_lazy('speciality', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']
        app_label = 'igis_udm'

    def __str__(self):
        return self.name


class DayofWeek(models.Model):
    WEEK_DAYS = (
        ('Пн', 'Понедельник'),
        ('Вт', 'Вторник'),
        ('Ср', 'Среда'),
        ('Чт', 'Четверг'),
        ('Пт', 'Пятница'),
        ('Сб', 'Суббота'),
        ('Вс', 'Воскресенье'),
    )

    name = models.CharField('день недели',
                            max_length=2,
                            unique=True,
                            choices=WEEK_DAYS)

    class Meta:
        app_label = 'igis_udm'

    def __str__(self):
        return self.get_name_display()


class FreeDay(models.Model):
    date = models.DateField()

    class Meta:
        app_label = 'igis_udm'

    def __str__(self):
        return self.date.strftime('%d.%m.%Y')


class Person(models.Model):
    igis_fio = models.CharField(max_length=255)
    igis_url = models.URLField(max_length=255)
    igis_person_id = models.CharField(max_length=255, blank=True, null=True)
    igis_update_date = models.DateTimeField(blank=True, null=True)
    family = models.CharField(max_length=255, blank=True, null=True)
    update_date = models.DateTimeField(auto_now=True)
    speciality = models.ForeignKey(Speciality, on_delete=None, blank=True, null=True)
    hospital = models.ForeignKey(Hospital, on_delete=None)
    room = models.CharField(max_length=255, blank=True, null=True)
    time_limit = models.CharField(max_length=255, blank=True, null=True)
    kod = models.CharField(max_length=255, blank=True, null=True)
    sector = models.CharField(max_length=512, blank=True, null=True)
    time_filter = models.CharField(max_length=255, blank=True, null=True)
    unit = models.CharField(max_length=255, blank=True, null=True)
    info = models.CharField(max_length=255, blank=True, null=True)
    free_days = models.ManyToManyField(FreeDay, verbose_name='нерабочие дни', blank=True)
    weekends = models.ManyToManyField(DayofWeek, verbose_name='выходные', blank=True)

    def __str__(self):
        return self.family

igis_udm/templates/igis_udm/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  {% if not debug %}
  {% include 'igis_udm/google_analitics.html' %}
  {% include 'igis_udm/yandex_verification.html' %}
  {% endif %}
  <title>{% block title %}Удмуртия. Запись на прием к врачу.{% endblock title %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="{% block meta_keywords %}Удмуртия, запись на прием к врачу{% endblock %}">
  <meta name="description" content="{% block meta_description %}Удмуртия. Запись на прием к врачу.{% endblock %}">
  <link rel="stylesheet" href="{% static 'css/w3.css' %}">
  {% block header_custom_css %}{% endblock %}
  {% block header_custom_js %}{% endblock %}
</head>
<body class="w3-light-grey">
<!--Navigation-->
{% block page_navigation %}{% endblock page_navigation %}
<!--end of navigation-->

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">
{% block page_container %}{% endblock page_container %}
</div>

<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p>
    <a href="{% url 'contacts' %}" target="_blank">Контакты</a>
  </p>
  <p>Работает на
    <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" rel="external">w3.css</a>
    и
    <a href="https://www.djangoproject.com/" target="_blank" rel="external">Django</a>
  </p>
</footer>
{% block bottom_custom_js %}{% endblock %}
</body>
</html>

igis_udm/templates/igis_udm/bottom_adv_block.html
{% if debug %}
    <div style="height:100px;background-color:maroon;">
    </div>
{% else %}
    <div style="height:100px;">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- udm_bottom_mobile -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:320px;height:50px"
         data-ad-client="ca-pub-4042588755149706"
         data-ad-slot="2312047194"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    </div>
{% endif %}

igis_udm/templates/igis_udm/contact.html
{% extends 'igis_udm/base.html' %}
{% load staticfiles %}

{% block title %}Отправьте письмо с Вашими пожеланиями, замечаниями и предлжениями.{% endblock %}
{% block meta_keywords %}Удмуртия, запись к врачу, обратная связь.{% endblock %}
{% block meta_description %}Удмуртия. Сервис записи к врачу. Обратная связь.{% endblock meta_description %}

{% block header_custom_css %}
<style>
{% include 'igis_udm/my_css.css' %}
</style>
{% endblock %}



{% block page_container %}

<div class="w3-row">
    <div class="w3-card-4 w3-content" style="max-width:600px;">
        <div class="w3-container w3-teal">
            <h2>Заполните все поля.</h2>
        </div>
        <form class="w3-container" action="{% url 'contacts' %}" method="post" autocomplete="off" novalidate="">
            {% csrf_token %}
            {% if form.non_field_errors %}
            {% for error in form.email.errors %}
            <p class="form_error">
                {{ error }}
            </p>
            {% endfor %}
            {% endif %}
            <p>
                <label for="{{ form.email.id_for_label }}" class="w3-text-teal"><b>Адрес: </b>{% if form.email.errors %}
                                                                                              {% for error in form.email.errors %}
                                                                                               <span class="form_error">
                                                                                                   {{ error }}
                                                                                               </span>
                                                                                              {% endfor %}
                                                                                              {% endif %}</label>
                <input class="w3-input w3-border w3-theme-l5" id="{{ form.email.id_for_label }}" name="{{ form.email.html_name }}" value="{{ form.email.value|default_if_none:'' }}" type="text" placeholder="Ваш email адрес"{% if form.email.errors %} style="border-color:red !important;"{% endif %}>
            </p>
            <p>
                <label for="{{ form.subject.id_for_label }}" class="w3-text-teal"><b>Тема: </b>{% if form.subject.errors %}
                                                                                              {% for error in form.subject.errors %}
                                                                                               <span class="form_error">
                                                                                                   {{ error }}
                                                                                               </span>
                                                                                              {% endfor %}
                                                                                              {% endif %}</label>
                <input class="w3-input w3-border w3-theme-l5" id="{{ form.subject.id_for_label }}" name="{{ form.subject.html_name }}" value="{{ form.subject.value|default_if_none:'' }}" type="text" placeholder="Тема письма"{% if form.subject.errors %} style="border-color:red !important;"{% endif %}>
            </p>
            <p>
                <label for="{{ form.message.id_for_label }}" class="w3-text-teal"><b>Письмо: </b>{% if form.message.errors %}
                                                                                              {% for error in form.message.errors %}
                                                                                               <span class="form_error">
                                                                                                   {{ error }}
                                                                                               </span>
                                                                                              {% endfor %}
                                                                                              {% endif %}</label>
                <textarea class="w3-input w3-border w3-theme-l5" id="{{ form.message.id_for_label }}" name="{{ form.message.html_name }}" style="resize:none;{% if form.message.errors %}border-color:red !important;{% endif %}" required>{{ form.message.value|default_if_none:'' }}</textarea>
            </p>
            <p>
                <button class="w3-btn w3-teal" type="submit">Отправить</button>
            </p>
        </form>
    </div>
</div>

{% endblock page_container %}

igis_udm/templates/igis_udm/contact_success.html
{% extends 'igis_udm/base.html' %}
{% load staticfiles %}

{% block title %}Спасибо за Ваше сообщение.{% endblock %}
{% block meta_keywords %}Удмуртия, запись к врачу, обратная связь, письмо отправлено{% endblock %}
{% block meta_description %}Удмуртия. Сервис записи к врачу. Обратная связь. Письмо отправлено.{% endblock meta_description %}

{% block header_custom_css %}
<style>
{% include 'igis_udm/my_css.css' %}
</style>
{% endblock %}



{% block page_container %}

<div class="w3-row">
    <div class="w3-card-4 w3-content" style="max-width:600px;">
        <div class="w3-container w3-teal">
            <h2>Письмо отправлено.</h2>
            <p>
                Спасибо за обращение. Если это будет возможно и необходимо мы постараемся ответить.
            </p>
            <hr>
            <p>
                <a href="{% url 'place_list' %}" title="Выберите город или район Удмуртии для записи к врачу.">Выбрать город или район Удмуртии.</a>
            </p>
        </div>
    </div>
</div>

{% endblock page_container %}

igis_udm/templates/igis_udm/google_analitics.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-112772987-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-112772987-1');
</script>

igis_udm/templates/igis_udm/hospital_form.html
{% extends "igis_udm/base.html" %}

{% block header_custom_css %}
<style>{% include 'igis_udm/modal_img_hospital_detail.css' %}</style>
{% endblock %}
{% block header_custom_js %}
{% endblock %}

{% block page_container %}
<div class="w3-row-padding">
    <!-- Left Column -->
    <div class="w3-third">
        {% block left_column %}
        <div class="w3-container w3-card-2 w3-white w3-margin-bottom  w3-display-container">
            <h6 class="w3-text-grey w3-padding-small"><a href="{{ hospital.place.get_absolute_url }}">{{ hospital.place.name }}</a></h6>
            <h5 class="w3-text-grey w3-padding-small">{{ hospital.name }}</h5>
            <button class="w3-button w3-block w3-teal w3-margin-bottom w3-left-align w3-round" onclick="w3.toggleClass('#hospital_info', 'w3-hide')">Детали <span class="w3-hide-small">(адрес, телефон, сайт)</span></button>
            <div id="hospital_info" class="w3-container w3-hide">
                <div class="w3-row">
                    <div class="w3-third w3-center w3-border-right w3-border-left">
                        <img id="myImg" width="200" src="{{ hospital.image.url }}" class="w3-image" title="{{ hospital.name }}" alt="{{ hospital.name }}">
                        <br>
                        <!-- The Modal -->
                        <div id="myModal" class="modal">
                            <!-- The Close Button -->
                            <span class="close" onclick="document.getElementById('myModal').style.display='none'">&times;</span>
                            <!-- Modal Content (The Image) -->
                            <img class="modal-content" id="img01">
                        </div>
                    </div>
                    <div class="w3-twothird w3-padding">
                        <p>{{ hospital.address }}</p>
                        <p>{{ hospital.phone }}</p>
                        <p><a href="{{ hospital.site_url }}" target="_blank">{{ hospital.site_url }}</a></p>
                        <p>{{ hospital.email }}</p>
                    </div>

                </div>
            </div>
        </div>
        <div class="w3-container w3-card-2 w3-white w3-margin-bottom">
            <div>
                <form class="w3-margin-bottom" method="post" name="login">{% csrf_token %}
                    {{ form.non_field_errors }}
                    <p>
                        {{ form.name.errors }}
                        <label class="w3-text-grey">Фамилия</label>
                        <input class="w3-input w3-border" name="ul" placeholder="иванов (только фамилия)">
                    </p>
                    <p>
                        {{ form.polis.errors }}
                        <label class="w3-text-grey">Номер полиса</label>
                        <input class="w3-input w3-border" name="up" placeholder="1111 2222 3333 4444 (только цифры)">
                    </p>
                    <p>
                        <button class="w3-button w3-block w3-teal w3-round">Авторизация</button>
                    </p>
                </form>
            </div>
        </div>
        <div class="w3-container w3-card-2 w3-white">
            <p>
                <button onclick="w3.toggleClass('#cities_list','w3-hide')" class="w3-button w3-block w3-left-align w3-teal w3-round">Выбрать город или район</button>
            </p>
            <div id="cities_list" class="w3-container w3-hide">
                <form class="w3-margin-bottom">
                    <p>
                        <label class="w3-text-grey">Фильтр по названию</label>
                        <input oninput="w3.filterHTML('#places_list', '.my_city', this.value)" class="w3-input w3-border">
                    </p>
                </form>
                <ul id="places_list" class="w3-ul">
                    {% for place in place_list %}
                    <li class="my_city"><a href="{{ place.get_absolute_url }}">{{ place.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endblock left_column %}
        <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
        {% block right_column %}
        <div class="w3-white w3-text-grey w3-card-4">
            <div class="w3-container">
                <div class="w3-row">
                    <div class="w3-half">
                        <form>
                            <p>
                                <label class="w3-text-grey">Фильтр по фамилии или специальности</label>
                                <input oninput="w3.filterHTML('#person_table', '.person_item', this.value)" class="w3-input w3-border">
                            </p>
                        </form>
                    </div>
                </div>
                <div class="">
                    <table id="person_table" class="w3-table-all">
                        <tr>
                            <th onclick="w3.sortHTML('#person_table','.person_item', 'td:nth-child(1)>a')" style="cursor:pointer">Ф.И.О.&nbsp;#&8645;</i></th>
                            <th onclick="w3.sortHTML('#person_table','.person_item', 'td:nth-child(2)')" style="cursor:pointer">Спец-ть&nbsp;#&8645;</th>
                            <th class="w3-hide-small">Информация</th>
                        </tr>
                        {% for person in person_list %}
                        <tr class="person_item">
                            <td><a onclick="document.getElementById('modal_container').style.display='block'" data-person-data-1="{{ person.data_1 }}" data-person-data-2="{{ person.data_2 }}" href="#">{{ person.fio|upper }}</a></td>
                            <td>{{ person.speciality }}</td>
                            <td class="w3-hide-small">{{ person.info }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <br>
            </div>
        </div>
    </div>
    {% endblock right_column %}
    <!-- End Right Column -->
</div>
<div id="modal_container" class="w3-modal">
    <div class="w3-modal-content w3-card-4 w3-animate-zoom">
        <header class="w3-container w3-teal">
            <span onclick="document.getElementById('modal_container').style.display='none'" class="w3-button w3-display-topright">&times;</span>
            <h2>Modal Header</h2>
        </header>
        <div class="w3-container">
            <p>Some text..</p>
            <p>Some text..</p>
        </div>
        <footer class="w3-container w3-teal">
            <p>Modal Footer</p>
        </footer>
    </div>
</div>
{% endblock page_container %}

{% block bottom_custom_js %}
<script>
{% include  'igis_udm/modal_img_hospital_detail.js' %}
</script>
{% endblock %}

igis_udm/templates/igis_udm/place_detail.html
{% extends "igis_udm/base.html" %}

{% block title %}Удмуртия. {{ place.name }}. Выбор медицинского учреждения.{% endblock title %}
{% block meta_keywords %}Удмуртия, {{ place.name }}, выбор больницы, запись к врачу.{% endblock %}
{% block meta_description %}Удмуртия. {{ place.name }}. Запись на прием к врачу. Выбор медицинского учреждения.{% endblock meta_description %}

{% block header_custom_css %}
{% endblock %}

{% block page_container %}
  <div class="w3-row-padding">
    <!-- Left Column -->
    <div class="w3-col l4 m6 s12">
        <div class="w3-display-container" style="height:120px;">
            <div class="w3-display-middle" style="height:100px;width:320px">
                <!-- Top advs block -->
                {% include 'igis_udm/top_adv_block.html' %}
                <!-- end of top advs -->
            </div>
        </div>

        {% block left_column %}
        <div class="w3-white w3-text-grey w3-card-4 w3-margin-bottom">
            <div class="w3-container">
                <h4>{{ place.name }}</h4>
            </div>
            <button onclick="toggle_class('cities_list','w3-hide')" class="w3-button w3-block w3-left-align w3-teal">Выбрать город или район</button>
            <div id="cities_list" class="w3-container w3-hide">
                <form class="w3-margin-bottom">
                    <p>
                        <label class="w3-text-grey">Фильтр по названию</label>
                        <input oninput="filterHTML('places_list', 'my_city', 'search_item', this.value)" class="w3-input w3-border" type="text">
                    </p>
                </form>
                <ul id="places_list" class="w3-ul">
                    {% for place in place_list %}
                    <li class="my_city"><a class="search_item" href="{{ place.get_absolute_url }}"  title="Запись к врачу. {{ place.name }}.">{{ place.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        {% if  place.hospital_set.all|length > 3 %}
        <div class="w3-container w3-teal">
            <h5>Фильтр</h5>
        </div>

        <form class="w3-container w3-card-4 w3-margin-bottom">
            <p>
                <label class="w3-text-grey">Название или адрес больницы</label>
                <input oninput="filterHTML('hospital_list', 'my_item', 'my_hospital_name', this.value)" class="w3-input w3-border" type="text">
            </p>
        </form>
        {% endif %}

        {% endblock left_column %}
    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div id="hospital_list" class="w3-col l8 m6 s12">
{% block right_column %}
      {% for hospital in place.hospital_set.all %}
      <div class="w3-container w3-card-2 w3-white w3-margin-bottom  my_item">
          <div class="w3-container">
            <h5 class="w3-text-dark-grey my_hospital_name" title="Запись на прием. {{ place.name }}. {{ hospital.name }}."><a href="{{ hospital.get_absolute_url }}" class="search_item">{{ hospital.name }}</a></h5>
            {% if hospital.phone %}<h6 class="w3-text-teal">&#9742; {{ hospital.phone }}</h6>{% endif %}
            <p class="w3-text-dark-grey">{{ hospital.address }}</p>
          </div>
      </div>
      {% endfor %}
{% endblock right_column %}
    <!-- End Right Column -->
    </div>

{% endblock page_container %}
  </div>

{% block bottom_custom_js %}
<script>
{% include  'igis_udm/my_utils.js' %}
</script>
{% endblock %}

igis_udm/templates/igis_udm/place_list.html
{% extends "igis_udm/base.html" %}
{% block title %}Удмуртия. Запись на прием к врачу. Выбор города или района.{% endblock title %}
{% block meta_keywords %}Удмуртия, выбор города, запись к врачу, интернет{% endblock %}
{% block meta_description %}Удмуртия. Запись на прием к врачу. Выбор города или района.{% endblock meta_description %}

{% block page_container %}
<div class="w3-row-padding"  itemscope itemtype="http://schema.org/Action" itemprop="name" value="Запись к врачу">
    <div class="w3-panel w3-white w3-text-teal w3-card w3-round" itemscope itemtype="http://schema.org/State" itemprop="location">
        <h1 itemprop="name" value="Удмуртия">Выберите город или район Удмуртии где Вы хотите записаться на прием.</h1>
    </div>
    <div class="w3-third">
        <div class="w3-white w3-text-grey w3-card-4">
            <ul class="w3-ul">
                {% for place in page_obj_1 %}
                <li><a href="{{ place.get_absolute_url }}" title="Запись к врачу. {{ place.name }}.">{{ place.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="w3-third">
        <div class="w3-white w3-text-grey w3-card-4">
            <ul class="w3-ul">
                {% for place in page_obj_2 %}
                   <li><a href="{{ place.get_absolute_url }}"  title="Запись к врачу. {{ place.name }}.">{{ place.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="w3-third">
        <div class="w3-white w3-text-grey w3-card-4">
            <ul class="w3-ul">
                {% for place in page_obj_3 %}
                   <li><a href="{{ place.get_absolute_url }}" title="Запись к врачу. {{ place.name }}.">{{ place.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<!-- Top advs block -->
{% include 'igis_udm/place_list_adv_bottom.html' %}
<!-- end of nop advs -->
{% endblock page_container %}

igis_udm/templates/igis_udm/place_list_adv_bottom.html
{% if debug %}
    <div class="w3-container w3-margin-top">
        <div class="w3-blue" style="height:100px;margin:auto;width:90%">
        </div>
    </div>
{% else %}
    <div class="w3-container w3-margin-top" style="height:100px;margin:auto;">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- udm_med_bottom -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-4042588755149706"
         data-ad-slot="5366797792"
         data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    </div>
{% endif %}

igis_udm/templates/igis_udm/top_adv_block.html
{% if debug %}
    <div id="foo" style="height:100px;background-color:maroon;">
    </div>
{% else %}
    <div style="height:100px;">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- udm_top_320_100 -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:320px;height:100px"
         data-ad-client="ca-pub-4042588755149706"
         data-ad-slot="3284193994"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    </div>
{% endif %}

igis_udm/templates/igis_udm/yandex_verification.html
<meta name="yandex-verification" content="558dafca3a09524b" />